server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation
    # active: dev
  data:
    redis:
      host: localhost
      port: 6379
      password: "123456"
      database: 11
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
